//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.Graywulf.Sql.Jobs.Query {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.Graywulf.Sql.Jobs.Query.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed statistics for table {0} in {1} sec. The number of records affected is {2}..
        /// </summary>
        public static string ComputedStatistics {
            get {
                return ResourceManager.GetString("ComputedStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated {0} partitions..
        /// </summary>
        public static string GeneratedPartitions {
            get {
                return ResourceManager.GetString("GeneratedPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output table {0} created on partition {1} with {2} in {3} sec. The number of records affected is {4}..
        /// </summary>
        public static string OutputTableCreated {
            get {
                return ResourceManager.GetString("OutputTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote output table {0} copied from partition {1} with {2} in {3} sec. The number of records affected is {4}..
        /// </summary>
        public static string RemoteOutputTableCopied {
            get {
                return ResourceManager.GetString("RemoteOutputTableCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified remote output table {0}..
        /// </summary>
        public static string RemoteOutputTableIdentified {
            get {
                return ResourceManager.GetString("RemoteOutputTableIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized remote output table {0}..
        /// </summary>
        public static string RemoteOutputTableInitialized {
            get {
                return ResourceManager.GetString("RemoteOutputTableInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote source table {0} copied to partition {1} with {2} in {3} sec. The number of records affected is {4}..
        /// </summary>
        public static string RemoteSourceTableCopied {
            get {
                return ResourceManager.GetString("RemoteSourceTableCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified remote source table {0}. It will be copied to worker node for query execution..
        /// </summary>
        public static string RemoteSourceTableIdentified {
            get {
                return ResourceManager.GetString("RemoteSourceTableIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server instance {0} is assigned to query partition {1}..
        /// </summary>
        public static string ServerInstanceAssignedPartition {
            get {
                return ResourceManager.GetString("ServerInstanceAssignedPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server instance {0} is assigned to query..
        /// </summary>
        public static string ServerInstanceAssignedQuery {
            get {
                return ResourceManager.GetString("ServerInstanceAssignedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified table {0} to gather statistics on..
        /// </summary>
        public static string StatisticsTableIdentified {
            get {
                return ResourceManager.GetString("StatisticsTableIdentified", resourceCulture);
            }
        }
    }
}
