//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.Graywulf.Web.Admin.Layout {
    
    
    public partial class FederationDetails {
        
        /// <summary>
        /// EntityChildren1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Admin.Controls.EntityChildren EntityChildren1;
        
        /// <summary>
        /// DatabaseDefinitionList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Admin.Controls.EntityList DatabaseDefinitionList;
        
        /// <summary>
        /// EntityButtons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Admin.Controls.EntityButtons EntityButtons;
    }
}
