//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.Graywulf.Install {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.Graywulf.Install.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剃䅅䕔䄠卓䵅䱂⁙䩛畨䜮慲睹汵⹦敒楧瑳祲䔮畮嵭਍啁䡔剏婉呁佉⁎摛潢൝䘊佒⁍⑛效嵸਍䥗䡔倠剅䥍卓佉彎䕓⁔‽䅓䕆਍਍佇਍.
        /// </summary>
        internal static string Jhu_Graywulf_Registry_Assembly {
            get {
                return ResourceManager.GetString("Jhu_Graywulf_Registry_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⴭ唠䕓⁒䕄䥆䕎吠偙卅ⴠഭഊ䌊䕒呁⁅奔䕐嬠扤嵯嬮敄汰祯敭瑮瑓瑡嵥਍塅䕔乒䱁丠䵁⁅䩛畨䜮慲睹汵⹦敒楧瑳祲䔮畮嵭嬮桊⹵片祡畷晬刮来獩牴⹹煓⹬敄汰祯敭瑮瑓瑡嵥਍਍佇਍਍਍剃䅅䕔吠偙⁅摛潢⹝䩛扯硅捥瑵潩卮慴整൝䔊员剅䅎⁌䅎䕍嬠桊⹵片祡畷晬刮来獩牴⹹湅浵⹝䩛畨䜮慲睹汵⹦敒楧瑳祲匮汱䨮扯硅捥瑵潩卮慴整൝ഊ䜊൏ഊഊ䌊䕒呁⁅奔䕐嬠扤嵯嬮畒湮湩卧慴整൝䔊员剅䅎⁌䅎䕍嬠桊⹵片祡畷晬刮来獩牴⹹湅浵⹝䩛畨䜮慲睹汵⹦敒楧瑳祲匮汱刮湵楮杮瑓瑡嵥਍਍佇਍਍਍剃䅅䕔吠偙⁅摛潢⹝卛档摥汵呥灹嵥਍塅䕔乒䱁丠䵁⁅䩛畨䜮慲睹汵⹦敒楧瑳祲䔮畮嵭嬮桊⹵片祡畷晬刮来獩牴⹹煓⹬捓敨畤敬祔数൝ഊ䜊൏ഊഊⴊ‭久䥔奔䘠乕呃佉华ⴠഭഊ䌊䕒呁⁅剐䍏嬠扤嵯嬮灳牃慥整湅楴祴൝ऊ啀敳䝲極⁤湵煩敵摩湥楴楦牥ബऊ਍䀉潃据牵敲据噹牥楳湯戠湩牡⡹⤸传呕啐ⱔ਍䀉畎扭牥椠瑮传呕啐ⱔ਍ഉऊ䝀極⁤湵煩敵摩湥楴楦牥ബऊ偀牡湥䝴極⁤湵煩敵摩湥楴楦牥ബऊ䕀瑮瑩呹灹⁥湩ⱴ਍䀉慎敭渠慶捲慨⡲㈱⤸ബऊ噀牥楳湯渠慶捲慨⡲㔲Ⱙ਍䀉畒湮湩卧慴整椠瑮ബऊ䅀敬瑲瑓瑡⁥湩ⱴ਍䀉敄汰祯敭瑮瑓瑡⁥湩ⱴ਍䀉慄整牃慥整⁤慤整楴敭ബऊ䑀瑡䵥摯晩敩⁤慤整楴敭ബऊ區瑥楴杮⁳癮牡档牡洨硡Ⱙ਍䀉潃浭湥獴渠慶捲慨⡲慭⥸ബऊ䕀瑮瑩剹晥 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jhu_Graywulf_Registry_Logic {
            get {
                return ResourceManager.GetString("Jhu_Graywulf_Registry_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⴭ䌠䕒呁⁅䅔䱂卅ⴠഭഊ䌊䕒呁⁅䅔䱂⁅摛潢⹝䕛瑮瑩嵹਍നऊ䝛極嵤嬠湵煩敵摩湥楴楦牥⁝低⁔啎䱌ബऊ䍛湯畣牲湥祣敖獲潩嵮嬠楴敭瑳浡嵰丠呏丠䱕ⱌ਍嬉慐敲瑮畇摩⁝畛楮畱楥敤瑮晩敩嵲丠呏丠䱕ⱌ਍嬉湅楴祴祔数⁝楛瑮⁝低⁔啎䱌ബऊ乛浵敢嵲嬠湩嵴丠呏丠䱕ⱌ਍嬉慎敭⁝湛慶捲慨嵲ㄨ㠲 ///低⁔啎䱌ബऊ噛牥楳湯⁝湛慶捲慨嵲㈨⤵丠呏丠䱕ⱌ਍嬉祓瑳浥⁝扛瑩⁝低⁔啎䱌ബऊ䡛摩敤嵮嬠楢嵴丠呏丠䱕ⱌ਍嬉敒摡湏祬⁝扛瑩⁝低⁔啎䱌ബऊ偛楲慭祲⁝扛瑩⁝低⁔啎䱌ബऊ䑛汥瑥摥⁝扛瑩⁝低⁔啎䱌ബऊ䱛捯佫湷牥⁝畛楮畱楥敤瑮晩敩嵲丠䱕ⱌ਍嬉畒湮湩卧慴整⁝楛瑮⁝低⁔啎䱌ബऊ䅛敬瑲瑓瑡嵥嬠湩嵴丠呏丠䱕ⱌ਍嬉敄汰祯敭瑮瑓瑡嵥嬠湩嵴丠呏丠䱕ⱌ਍嬉獕牥畇摩睏敮嵲嬠湵煩敵摩湥楴楦牥⁝低⁔啎䱌ബऊ䑛瑡䍥敲瑡摥⁝摛瑡瑥浩嵥丠呏丠䱕ⱌ਍嬉獕牥畇摩牃慥整嵤嬠湵煩敵摩湥楴楦牥⁝低⁔啎䱌ബऊ䑛瑡䵥摯晩敩嵤嬠慤整楴敭⁝低⁔啎䱌ബऊ啛敳䝲極䵤摯晩敩嵤嬠湵煩敵摩湥楴楦牥⁝低⁔啎䱌ബऊ䑛瑡䑥汥瑥摥⁝摛瑡瑥浩嵥丠䱕ⱌ਍嬉獕牥畇摩敄敬整嵤嬠湵煩敵摩湥楴楦牥⁝啎䱌ബऊ卛瑥楴杮嵳嬠浸嵬丠䱕ⱌ਍嬉潃浭湥獴⁝湛慶捲慨嵲洨硡 ///低⁔啎䱌ബऊ佃华剔䥁呎嬠䭐䕟瑮瑩嵹倠䥒䅍奒䬠奅䌠啌呓剅䑅ഠऊനऊ嬉畇摩⁝十ൃऊഩ⤊ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jhu_Graywulf_Registry_Tables {
            get {
                return ResourceManager.GetString("Jhu_Graywulf_Registry_Tables", resourceCulture);
            }
        }
    }
}
