//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.Graywulf.Web.Services.CodeGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Swagger {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Swagger() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.Graywulf.Web.Services.CodeGen.Swagger", typeof(Swagger).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   __className__:
        ///    properties:
        ///.
        /// </summary>
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definitions:
        ///.
        /// </summary>
        internal static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swagger: &quot;2.0&quot;
        ///info:
        ///  title: &quot;__apiTitle__&quot;
        ///  description: &quot;__apiDescription__&quot;
        ///  version: &quot;__apiVersion__&quot;
        ///
        ///schemes: 
        ///  - &quot;http&quot;
        ///  - &quot;https&quot;
        ///host: &quot;__hostName__&quot;
        ///basePath: &quot;__basePath__&quot;
        ///consumes: 
        ///  - &quot;application/json&quot;
        ///produces: 
        ///  - &quot;application/json&quot;
        ///
        ///.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     __httpMethod__: 
        ///      tags:
        ///        - __serviceName__
        ///      description: &quot;&quot;
        ///      operationId: &quot;__operationName__&quot;
        ///      produces: 
        ///        - &quot;application/json&quot;
        ///        - &quot;application/xml&quot;
        ///        - &quot;text/xml&quot;
        ///      responses: 
        ///        &quot;200&quot;:
        ///          description: &quot;__operationName__ response&quot;
        ///        default: 
        ///          description: &quot;unexpected error&quot;
        ///      parameters: 
        ///.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         - name: &quot;__parameterName__&quot;
        ///          in: &quot;__parameterIn__&quot;
        ///          description: &quot;__parameterDescription__&quot;
        ///          required: false
        ///          __parameterType__
        ///.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   __path__: 
        ///.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paths:
        ///.
        /// </summary>
        internal static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       __parameterName__:
        ///        __parameterType__
        ///.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
    }
}
