

CREATE TABLE [dbo].[TestTable]
(
	[OBJID] [bigint] NOT NULL,
	[RA] [float] NOT NULL,
	[Dec] [float] NOT NULL,
	CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED 
	(
		[OBJID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


